(()=>{'use strict';
const $=s=>document.querySelector(s),MAX_FILES=100,MAX_BYTES=200*1024*1024;let items=[],busy=false,seq=0;
const labels={
  ja:{title:'画像 → PDF',add:'画像を追加',make:'PDFを作成',empty:'JPG・PNG・WebPを追加',tooMany:'画像は100枚までです',tooLarge:'合計200MBを超えています',working:'PDFを作成中…',failed:'PDFを作成できませんでした',pageSize:'ページサイズ',margin:'余白',fit:'配置',auto:'画像に合わせる',a4:'A4',letter:'Letter',contain:'全体を収める',cover:'全面に敷く',quality:'画質',name:'ファイル名',drop:'ここへ画像をドロップ',duplicate:'同じ画像は追加済みです',images:'枚'},
  en:{title:'Images → PDF',add:'Add images',make:'Create PDF',empty:'Add JPG, PNG or WebP images',tooMany:'Up to 100 images',tooLarge:'Combined size exceeds 200 MB',working:'Creating PDF…',failed:'Could not create PDF',pageSize:'Page size',margin:'Margin',fit:'Fit',auto:'Match image',a4:'A4',letter:'Letter',contain:'Contain',cover:'Cover',quality:'Quality',name:'File name',drop:'Drop images here',duplicate:'That image is already added',images:'images'},
  zh:{title:'图片 → PDF',add:'添加图片',make:'创建 PDF',empty:'添加 JPG、PNG 或 WebP 图片',tooMany:'最多100张图片',tooLarge:'总大小超过200MB',working:'正在创建 PDF…',failed:'无法创建 PDF',pageSize:'页面尺寸',margin:'边距',fit:'适配',auto:'匹配图片',a4:'A4',letter:'Letter',contain:'完整显示',cover:'铺满页面',quality:'画质',name:'文件名',drop:'拖放图片到这里',duplicate:'该图片已添加',images:'张'},
  ko:{title:'이미지 → PDF',add:'이미지 추가',make:'PDF 만들기',empty:'JPG, PNG, WebP 이미지를 추가하세요',tooMany:'이미지는 100장까지 가능합니다',tooLarge:'합계 200MB를 초과했습니다',working:'PDF 만드는 중…',failed:'PDF를 만들 수 없습니다',pageSize:'페이지 크기',margin:'여백',fit:'맞춤',auto:'이미지에 맞춤',a4:'A4',letter:'Letter',contain:'전체 표시',cover:'가득 채우기',quality:'화질',name:'파일 이름',drop:'여기에 이미지를 놓으세요',duplicate:'이미 추가된 이미지입니다',images:'장'}
};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(labels[lang()]||labels.en)[k]||k;
function toast(text,ms=2600){const e=$('#status');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),ms)}
function human(bytes){return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function totalBytes(next=[]){return[...items,...next].reduce((n,x)=>n+(x.file?.size||x.size||0),0)}
function safeImage(file){return file&&(/^image\/(jpeg|png|webp)$/i.test(file.type)||/\.(jpe?g|png|webp)$/i.test(file.name||''))}
function keyFor(file){return`${file.name}\n${file.size}\n${file.lastModified||0}`}
function sanitizeName(value){const raw=String(value||'images').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\.pdf$/i,'');return(raw||'images').slice(0,120)}
function updateSummary(){const count=$('#imagePdfCount');if(count)count.textContent=items.length?`${items.length} ${t('images')} · ${human(totalBytes())}`:t('empty');const make=$('#imagePdfMake');if(make)make.disabled=busy||!items.length}
function move(index,delta){const to=index+delta;if(to<0||to>=items.length||busy)return;[items[index],items[to]]=[items[to],items[index]];render()}
function remove(index){if(busy)return;items.splice(index,1);render()}
function reorder(from,to){if(from===to||from<0||to<0||from>=items.length||to>=items.length||busy)return;const[moved]=items.splice(from,1);items.splice(to,0,moved);render()}
function render(){const list=$('#imagePdfList');if(!list)return;list.replaceChildren();items.forEach((item,i)=>{const row=document.createElement('div');row.className='image-pdf-row';row.draggable=!busy;row.dataset.index=String(i);const preview=document.createElement('img');preview.alt='';preview.src=item.url;const meta=document.createElement('div');const name=document.createElement('strong');name.textContent=item.file.name;const small=document.createElement('small');small.textContent=human(item.file.size);meta.append(name,small);const actions=document.createElement('div');for(const[label,delta]of[['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='merge-mini';b.textContent=label;b.disabled=busy||(delta<0?i===0:i===items.length-1);b.onclick=()=>move(i,delta);actions.append(b)}const del=document.createElement('button');del.type='button';del.className='merge-mini danger';del.textContent='×';del.disabled=busy;del.onclick=()=>remove(i);actions.append(del);row.addEventListener('dragstart',e=>{row.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i))});row.addEventListener('dragend',()=>row.classList.remove('dragging'));row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drag-over')});row.addEventListener('dragleave',()=>row.classList.remove('drag-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drag-over');const from=Number(e.dataTransfer.getData('text/plain'));reorder(from,i)});row.append(preview,meta,actions);list.append(row)});updateSummary()}
function add(fileList){const seen=new Set(items.map(x=>x.key)),incoming=[];let duplicate=false;for(const file of[...fileList]){if(!safeImage(file))continue;const key=keyFor(file);if(seen.has(key)){duplicate=true;continue}seen.add(key);incoming.push({id:++seq,key,file,url:URL.createObjectURL(file)})}if(!incoming.length){if(duplicate)toast(t('duplicate'));return}if(items.length+incoming.length>MAX_FILES){incoming.forEach(x=>URL.revokeObjectURL(x.url));toast(t('tooMany'));return}if(totalBytes(incoming)>MAX_BYTES){incoming.forEach(x=>URL.revokeObjectURL(x.url));toast(t('tooLarge'));return}items.push(...incoming);const box=$('#imagePdfBox');if(box)box.open=true;render();if(duplicate)toast(t('duplicate'))}
async function bitmapFor(file){if('createImageBitmap'in window){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{try{return await createImageBitmap(file)}catch{}}}const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}finally{setTimeout(()=>URL.revokeObjectURL(url),0)}}
function pageDimensions(mode,w,h){if(mode==='a4')return w>=h?[841.89,595.28]:[595.28,841.89];if(mode==='letter')return w>=h?[792,612]:[612,792];const scale=72/96,max=2000,min=72;return[Math.max(min,Math.min(max,w*scale)),Math.max(min,Math.min(max,h*scale))]}
async function jpegBytesFor(item,quality){const bmp=await bitmapFor(item.file),w=bmp.width||bmp.naturalWidth,h=bmp.height||bmp.naturalHeight;if(!w||!h)throw new Error('bad image');let scale=1;const maxPixels=24_000_000;if(w*h>maxPixels)scale=Math.sqrt(maxPixels/(w*h));const cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),canvas=document.createElement('canvas');canvas.width=cw;canvas.height=ch;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,cw,ch);ctx.drawImage(bmp,0,0,cw,ch);if(typeof bmp.close==='function')bmp.close();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('encode failed')),'image/jpeg',quality));return{bytes:await blob.arrayBuffer(),width:w,height:h}}
function setBusy(on){busy=on;const box=$('#imagePdfBox');if(box)box.dataset.busy=on?'1':'0';render()}
async function createPdf(){if(busy||!items.length)return;setBusy(true);toast(t('working'));try{const out=await PDFLib.PDFDocument.create(),mode=$('#imagePdfSize').value,marginMm=Number($('#imagePdfMargin').value)||0,fit=$('#imagePdfFit').value,quality=(Number($('#imagePdfQuality').value)||90)/100,margin=marginMm*72/25.4;for(let i=0;i<items.length;i++){const progress=$('#imagePdfCount');if(progress)progress.textContent=`${i+1}/${items.length} · ${t('working')}`;const imgData=await jpegBytesFor(items[i],quality),embedded=await out.embedJpg(imgData.bytes),[pw,ph]=pageDimensions(mode,imgData.width,imgData.height),page=out.addPage([pw,ph]),availW=Math.max(1,pw-margin*2),availH=Math.max(1,ph-margin*2),ratio=fit==='cover'?Math.max(availW/embedded.width,availH/embedded.height):Math.min(availW/embedded.width,availH/embedded.height),dw=embedded.width*ratio,dh=embedded.height*ratio,x=(pw-dw)/2,y=(ph-dh)/2;page.drawImage(embedded,{x,y,width:dw,height:dh})}const title=sanitizeName($('#imagePdfName').value);out.setTitle(title);out.setCreator('PDF WORKBENCH');out.setProducer('PDF WORKBENCH');const bytes=await out.save({useObjectStreams:true}),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${title}.pdf`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);toast((window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.saved||'PDF exported')}catch(e){console.warn(e);toast(t('failed'),3200)}finally{setBusy(false)}}
function relabel(){const box=$('#imagePdfBox');if(!box)return;box.querySelector('.image-pdf-title').textContent=t('title');box.querySelector('.image-pdf-add-text').textContent=t('add');box.querySelector('.image-pdf-drop').textContent=t('drop');box.querySelector('[for=imagePdfSize] span').textContent=t('pageSize');box.querySelector('[for=imagePdfMargin] span').textContent=t('margin');box.querySelector('[for=imagePdfFit] span').textContent=t('fit');box.querySelector('[for=imagePdfQuality] span').textContent=t('quality');box.querySelector('[for=imagePdfName] span').textContent=t('name');$('#imagePdfSize').options[0].text=t('auto');$('#imagePdfSize').options[1].text=t('a4');$('#imagePdfSize').options[2].text=t('letter');$('#imagePdfFit').options[0].text=t('contain');$('#imagePdfFit').options[1].text=t('cover');$('#imagePdfMake').textContent=t('make');updateSummary()}
function init(){const side=$('.panel.side');if(!side||$('#imagePdfBox')||!window.PDFLib)return;const box=document.createElement('details');box.id='imagePdfBox';box.className='image-pdf-box';box.innerHTML='<summary class="image-pdf-title"></summary><div class="image-pdf-body"><label class="button image-pdf-add" for="imagePdfInput">＋ <span class="image-pdf-add-text"></span></label><input id="imagePdfInput" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" multiple hidden><div class="image-pdf-drop" tabindex="0"></div><div id="imagePdfList" class="image-pdf-list"></div><small id="imagePdfCount"></small><div class="image-pdf-options"><label for="imagePdfSize"><span></span><select id="imagePdfSize"><option value="auto"></option><option value="a4"></option><option value="letter"></option></select></label><label for="imagePdfMargin"><span></span><select id="imagePdfMargin"><option value="0">0 mm</option><option value="5">5 mm</option><option value="10" selected>10 mm</option><option value="20">20 mm</option></select></label><label for="imagePdfFit"><span></span><select id="imagePdfFit"><option value="contain"></option><option value="cover"></option></select></label><label for="imagePdfQuality"><span></span><select id="imagePdfQuality"><option value="82">82%</option><option value="90" selected>90%</option><option value="96">96%</option></select></label><label for="imagePdfName"><span></span><input id="imagePdfName" value="images" maxlength="120"></label></div><button id="imagePdfMake" class="button primary" type="button" disabled></button><small>Local-only. Images are decoded and embedded in your browser; nothing is uploaded.</small></div>';side.append(box);$('#imagePdfInput').onchange=e=>{add(e.target.files||[]);e.target.value=''};const drop=box.querySelector('.image-pdf-drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');add(e.dataTransfer.files||[])});drop.addEventListener('click',()=>$('#imagePdfInput').click());drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#imagePdfInput').click()}});$('#imagePdfMake').onclick=createPdf;$('#languageSelect')?.addEventListener('change',()=>setTimeout(relabel));relabel();render()}
window.addEventListener('beforeunload',()=>items.forEach(x=>URL.revokeObjectURL(x.url)));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();