(()=>{'use strict';
const $=s=>document.querySelector(s),MAX_FILES=30,MAX_BYTES=200*1024*1024,MAX_PAGES=1500;let files=[],busy=false,seq=0;
const labels={ja:{title:'PDF結合',add:'PDFを追加',merge:'結合して保存',empty:'PDFを2個以上追加',tooMany:'PDFは30ファイルまでです',tooLarge:'合計200MBを超えています',working:'PDFを結合中…',failed:'PDFを結合できませんでした',encrypted:'パスワード保護PDFは結合できません',pages:'ページ'},en:{title:'Merge PDFs',add:'Add PDFs',merge:'Merge and save',empty:'Add at least two PDFs',tooMany:'Up to 30 PDF files',tooLarge:'Combined size exceeds 200 MB',working:'Merging PDFs…',failed:'Could not merge PDFs',encrypted:'Password-protected PDFs cannot be merged',pages:'pages'},zh:{title:'合并 PDF',add:'添加 PDF',merge:'合并并保存',empty:'请至少添加两个 PDF',tooMany:'最多30个PDF文件',tooLarge:'总大小超过200MB',working:'正在合并 PDF…',failed:'无法合并 PDF',encrypted:'无法合并受密码保护的PDF',pages:'页'},ko:{title:'PDF 합치기',add:'PDF 추가',merge:'합쳐서 저장',empty:'PDF를 2개 이상 추가하세요',tooMany:'PDF는 30개까지 가능합니다',tooLarge:'합계 200MB를 초과했습니다',working:'PDF 합치는 중…',failed:'PDF를 합칠 수 없습니다',encrypted:'암호로 보호된 PDF는 합칠 수 없습니다',pages:'페이지'}};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(labels[lang()]||labels.en)[k]||k;
function toast(text){const e=$('#status');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2800)}
function totalBytes(next=[]){return[...files,...next].reduce((n,x)=>n+(x.file?.size||x.size||0),0)}
function safePdf(file){return file&&(file.type==='application/pdf'||/\.pdf$/i.test(file.name||''))}
function human(bytes){return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function render(){const list=$('#mergeList');if(!list)return;list.replaceChildren();files.forEach((item,i)=>{const row=document.createElement('div');row.className='merge-row';const meta=document.createElement('div'),name=document.createElement('strong'),small=document.createElement('small');name.textContent=item.file.name;small.textContent=human(item.file.size);meta.append(name,small);const actions=document.createElement('div');for(const [label,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='merge-mini';b.textContent=label;b.disabled=busy||(delta<0?i===0:i===files.length-1);b.onclick=()=>move(i,delta);actions.append(b)}const remove=document.createElement('button');remove.type='button';remove.className='merge-mini danger';remove.textContent='×';remove.disabled=busy;remove.onclick=()=>{files.splice(i,1);render()};actions.append(remove);row.append(meta,actions);list.append(row)});$('#mergeButton').disabled=busy||files.length<2;$('#mergeCount').textContent=files.length?`${files.length} files · ${human(totalBytes())}`:t('empty')}
function move(index,delta){const to=index+delta;if(to<0||to>=files.length)return;[files[index],files[to]]=[files[to],files[index]];render()}
function add(fileList){const incoming=[...fileList].filter(safePdf).map(file=>({id:++seq,file}));if(!incoming.length)return;if(files.length+incoming.length>MAX_FILES){toast(t('tooMany'));return}if(totalBytes(incoming)>MAX_BYTES){toast(t('tooLarge'));return}files.push(...incoming);render()}
function download(blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='merged.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
async function merge(){if(busy||files.length<2){toast(t('empty'));return}if(totalBytes()>MAX_BYTES){toast(t('tooLarge'));return}busy=true;render();toast(t('working'));try{const out=await PDFLib.PDFDocument.create();let pages=0;for(let i=0;i<files.length;i++){const raw=await files[i].file.arrayBuffer();let src;try{src=await PDFLib.PDFDocument.load(raw,{ignoreEncryption:false,updateMetadata:false})}catch(e){if(/encrypt/i.test(`${e?.name||''} ${e?.message||''}`))throw new Error('encrypted');throw e}const count=src.getPageCount();pages+=count;if(pages>MAX_PAGES)throw new Error('pages');const copied=await out.copyPages(src,src.getPageIndices());copied.forEach(page=>out.addPage(page));$('#mergeCount').textContent=`${i+1}/${files.length} · ${pages} ${t('pages')}`;await new Promise(requestAnimationFrame)}out.setTitle('Merged PDF');out.setProducer('PDF WORKBENCH');out.setCreator('PDF WORKBENCH');const bytes=await out.save({useObjectStreams:true});download(new Blob([bytes],{type:'application/pdf'}));toast((window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.saved||'PDF exported')}catch(e){console.warn(e);toast(e?.message==='encrypted'?t('encrypted'):e?.message==='pages'?(window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.tooMany||t('failed'):t('failed'))}finally{busy=false;render()}}
function relabel(){const box=$('#mergeBox');if(!box)return;box.querySelector('.merge-title').textContent=t('title');box.querySelector('.merge-add').lastChild.textContent=` ${t('add')}`;$('#mergeButton').textContent=t('merge');render()}
function init(){const side=$('.panel.side');if(!side||$('#mergeBox'))return;const box=document.createElement('details');box.id='mergeBox';box.className='merge-box';box.innerHTML='<summary class="merge-title"></summary><div class="merge-body"><label class="button merge-add" for="mergeInput">＋<span></span></label><input id="mergeInput" type="file" accept=".pdf,application/pdf" multiple hidden><div id="mergeList" class="merge-list"></div><small id="mergeCount"></small><button id="mergeButton" class="button primary" type="button" disabled></button><small>Files stay in this browser. Forms and interactive PDF features may not survive page copying.</small></div>';side.append(box);$('#mergeInput').onchange=e=>{add(e.target.files||[]);e.target.value=''};$('#mergeButton').onclick=merge;$('#languageSelect')?.addEventListener('change',()=>setTimeout(relabel));relabel()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();