(()=>{'use strict';
const $=s=>document.querySelector(s),MAX_FILES=30,MAX_BYTES=200*1024*1024,MAX_PAGES=1500;let files=[],busy=false,seq=0,dragIndex=-1;
const labels={
  ja:{title:'PDF結合',add:'PDFを追加',merge:'結合して保存',empty:'PDFを2個以上追加',tooMany:'PDFは30ファイルまでです',tooLarge:'合計200MBを超えています',working:'PDFを結合中…',failed:'PDFを結合できませんでした',encrypted:'パスワード保護PDFは結合できません',pages:'ページ',drop:'ここへPDFをドロップ',duplicate:'同じPDFは追加済みです',name:'ファイル名',scanning:'確認中…'},
  en:{title:'Merge PDFs',add:'Add PDFs',merge:'Merge and save',empty:'Add at least two PDFs',tooMany:'Up to 30 PDF files',tooLarge:'Combined size exceeds 200 MB',working:'Merging PDFs…',failed:'Could not merge PDFs',encrypted:'Password-protected PDFs cannot be merged',pages:'pages',drop:'Drop PDFs here',duplicate:'That PDF is already added',name:'File name',scanning:'Checking…'},
  zh:{title:'合并 PDF',add:'添加 PDF',merge:'合并并保存',empty:'请至少添加两个 PDF',tooMany:'最多30个PDF文件',tooLarge:'总大小超过200MB',working:'正在合并 PDF…',failed:'无法合并 PDF',encrypted:'无法合并受密码保护的PDF',pages:'页',drop:'拖放 PDF 到这里',duplicate:'该 PDF 已添加',name:'文件名',scanning:'检查中…'},
  ko:{title:'PDF 합치기',add:'PDF 추가',merge:'합쳐서 저장',empty:'PDF를 2개 이상 추가하세요',tooMany:'PDF는 30개까지 가능합니다',tooLarge:'합계 200MB를 초과했습니다',working:'PDF 합치는 중…',failed:'PDF를 합칠 수 없습니다',encrypted:'암호로 보호된 PDF는 합칠 수 없습니다',pages:'페이지',drop:'여기에 PDF를 놓으세요',duplicate:'이미 추가된 PDF입니다',name:'파일 이름',scanning:'확인 중…'}
};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(labels[lang()]||labels.en)[k]||k;
function toast(text,ms=2800){const e=$('#status');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),ms)}
function setState(state,error=''){const box=$('#mergeBox');if(!box)return;box.dataset.state=state;if(error)box.dataset.error=error;else delete box.dataset.error}
function totalBytes(next=[]){return[...files,...next].reduce((n,x)=>n+(x.file?.size||x.size||0),0)}
function safePdf(file){return file&&(file.type==='application/pdf'||/\.pdf$/i.test(file.name||''))}
function keyFor(file){return`${file.name}\n${file.size}\n${file.lastModified||0}`}
function human(bytes){return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function safeName(value){const raw=String(value||'merged').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\.pdf$/i,'');return(raw||'merged').slice(0,120)}
function totalKnownPages(){return files.reduce((n,x)=>n+(Number.isFinite(x.pages)?x.pages:0),0)}
function render(){const list=$('#mergeList');if(!list)return;list.replaceChildren();files.forEach((item,i)=>{const row=document.createElement('div');row.className='merge-row';row.draggable=!busy;row.dataset.index=String(i);const meta=document.createElement('div'),name=document.createElement('strong'),small=document.createElement('small');name.textContent=item.file.name;small.textContent=item.error?t(item.error):item.pages==null?`${human(item.file.size)} · ${t('scanning')}`:`${human(item.file.size)} · ${item.pages} ${t('pages')}`;meta.append(name,small);const actions=document.createElement('div');for(const[label,delta]of[['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='merge-mini';b.textContent=label;b.disabled=busy||(delta<0?i===0:i===files.length-1);b.onclick=()=>move(i,delta);actions.append(b)}const remove=document.createElement('button');remove.type='button';remove.className='merge-mini danger';remove.textContent='×';remove.disabled=busy;remove.onclick=()=>{files.splice(i,1);setState('ready');render()};actions.append(remove);row.addEventListener('dragstart',e=>{dragIndex=i;row.classList.add('dragging');e.dataTransfer.effectAllowed='move'});row.addEventListener('dragend',()=>{dragIndex=-1;row.classList.remove('dragging')});row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drag-over')});row.addEventListener('dragleave',()=>row.classList.remove('drag-over'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drag-over');if(dragIndex<0||dragIndex===i)return;const[moved]=files.splice(dragIndex,1);files.splice(i,0,moved);dragIndex=-1;render()});row.append(meta,actions);list.append(row)});const invalid=files.some(x=>x.error),scanning=files.some(x=>x.pages==null&&!x.error);$('#mergeButton').disabled=busy||files.length<2||invalid||scanning;const pages=totalKnownPages(),base=files.length?`${files.length} files · ${human(totalBytes())}`:t('empty');$('#mergeCount').textContent=files.length&&pages?`${base} · ${pages} ${t('pages')}`:base}
function move(index,delta){const to=index+delta;if(to<0||to>=files.length||busy)return;[files[index],files[to]]=[files[to],files[index]];setState('ready');render()}
async function inspect(item){try{const raw=await item.file.arrayBuffer(),src=await PDFLib.PDFDocument.load(raw,{ignoreEncryption:false,updateMetadata:false});item.pages=src.getPageCount();if(totalKnownPages()>MAX_PAGES)item.error='tooMany'}catch(e){item.error=/encrypt/i.test(`${e?.name||''} ${e?.message||''}`)?'encrypted':'failed';item.pages=0}render()}
function add(fileList){const seen=new Set(files.map(x=>x.key)),incoming=[];let duplicate=false;for(const file of[...fileList]){if(!safePdf(file))continue;const key=keyFor(file);if(seen.has(key)){duplicate=true;continue}seen.add(key);incoming.push({id:++seq,key,file,pages:null,error:''})}if(!incoming.length){if(duplicate)toast(t('duplicate'));return}if(files.length+incoming.length>MAX_FILES){toast(t('tooMany'));return}if(totalBytes(incoming)>MAX_BYTES){toast(t('tooLarge'));return}files.push(...incoming);const box=$('#mergeBox');if(box)box.open=true;setState('ready');render();incoming.forEach(inspect);if(duplicate)toast(t('duplicate'))}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${safeName(name)}.pdf`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
async function merge(){if(busy||files.length<2){toast(t('empty'));return}if(totalBytes()>MAX_BYTES){toast(t('tooLarge'));return}if(files.some(x=>x.error||x.pages==null)){toast(t('failed'));return}busy=true;setState('working');render();toast(t('working'));try{const out=await PDFLib.PDFDocument.create();let pages=0;for(let i=0;i<files.length;i++){const raw=await files[i].file.arrayBuffer(),src=await PDFLib.PDFDocument.load(raw,{ignoreEncryption:false,updateMetadata:false}),count=src.getPageCount();pages+=count;if(pages>MAX_PAGES)throw new Error('pages');const indexes=Array.from({length:count},(_,n)=>n),copied=await out.copyPages(src,indexes);copied.forEach(page=>out.addPage(page));$('#mergeCount').textContent=`${i+1}/${files.length} · ${pages} ${t('pages')}`;await new Promise(resolve=>setTimeout(resolve,0))}const title=safeName($('#mergeName').value);out.setTitle(title);out.setProducer('PDF WORKBENCH');out.setCreator('PDF WORKBENCH');const bytes=await out.save({useObjectStreams:true});download(new Blob([bytes],{type:'application/pdf'}),title);setState('done');toast((window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.saved||'PDF exported')}catch(e){console.warn(e);const code=e?.message||'unknown';setState('error',code);toast(code==='pages'?(window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.tooMany||t('failed'):t('failed'))}finally{busy=false;render()}}
function relabel(){const box=$('#mergeBox');if(!box)return;box.querySelector('.merge-title').textContent=t('title');box.querySelector('.merge-add-text').textContent=t('add');box.querySelector('.merge-drop').textContent=t('drop');box.querySelector('[for=mergeName] span').textContent=t('name');$('#mergeButton').textContent=t('merge');render()}
function init(){const side=$('.panel.side');if(!side||$('#mergeBox')||!window.PDFLib)return;const box=document.createElement('details');box.id='mergeBox';box.className='merge-box';box.dataset.state='empty';box.innerHTML='<summary class="merge-title"></summary><div class="merge-body"><label class="button merge-add" for="mergeInput">＋ <span class="merge-add-text"></span></label><input id="mergeInput" type="file" accept=".pdf,application/pdf" multiple hidden><div class="merge-drop" tabindex="0"></div><div id="mergeList" class="merge-list"></div><small id="mergeCount"></small><label class="merge-name" for="mergeName"><span></span><input id="mergeName" value="merged" maxlength="120"></label><button id="mergeButton" class="button primary" type="button" disabled></button><small>Files stay in this browser. Forms and interactive PDF features may not survive page copying.</small></div>';side.append(box);$('#mergeInput').onchange=e=>{add(e.target.files||[]);e.target.value=''};const drop=box.querySelector('.merge-drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');add(e.dataTransfer.files||[])});drop.addEventListener('click',()=>$('#mergeInput').click());drop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#mergeInput').click()}});$('#mergeButton').onclick=merge;$('#languageSelect')?.addEventListener('change',()=>setTimeout(relabel));relabel()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();