(()=>{'use strict';
const $=s=>document.querySelector(s);let running=false;
if(window.pdfjsLib&&!window.__pdfWorkbenchSafeDataClone){const originalLib=window.pdfjsLib,originalGetDocument=originalLib.getDocument.bind(originalLib);window.pdfjsLib={...originalLib,getDocument(source){if(source&&typeof source==='object'&&source.data instanceof Uint8Array)source={...source,data:source.data.slice()};return originalGetDocument(source)}};window.__pdfWorkbenchSafeDataClone=true}
const labels={
  ja:{title:'ページ抽出',hint:'例: 1-3,5,last / odd / even',current:'現在ページ',range:'指定ページを書き出す',invalid:'ページ指定を確認してください',working:'編集内容を反映して抽出中…',failed:'ページ抽出に失敗しました',help:'1-3,5 / 3- / -4 / odd / even / all / last が使えます'},
  en:{title:'Extract pages',hint:'e.g. 1-3,5,last / odd / even',current:'Current page',range:'Export selected pages',invalid:'Check the page range',working:'Applying edits and extracting…',failed:'Could not extract pages',help:'Supports 1-3,5 / 3- / -4 / odd / even / all / last'},
  zh:{title:'提取页面',hint:'例如 1-3,5,last / odd / even',current:'当前页',range:'导出指定页面',invalid:'请检查页面范围',working:'正在应用编辑并提取…',failed:'页面提取失败',help:'支持 1-3,5 / 3- / -4 / odd / even / all / last'},
  ko:{title:'페이지 추출',hint:'예: 1-3,5,last / odd / even',current:'현재 페이지',range:'지정 페이지 내보내기',invalid:'페이지 범위를 확인하세요',working:'편집 내용을 적용해 추출 중…',failed:'페이지 추출 실패',help:'1-3,5 / 3- / -4 / odd / even / all / last 지원'}
};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(labels[lang()]||labels.en)[k]||k;
function totalPages(){const m=$('#pageTotal')?.textContent.match(/\d+/);return m?Number(m[0]):0}
function parseAtom(value,total){const s=String(value||'').trim().toLowerCase();if(!s)return null;if(s==='all')return Array.from({length:total},(_,i)=>i+1);if(s==='odd')return Array.from({length:total},(_,i)=>i+1).filter(n=>n%2===1);if(s==='even')return Array.from({length:total},(_,i)=>i+1).filter(n=>n%2===0);if(s==='last')return total?[total]:[];let m=s.match(/^(\d+)$/);if(m)return[Number(m[1])];m=s.match(/^(\d+)\s*-\s*(\d+)$/);if(m){const a=Number(m[1]),b=Number(m[2]),out=[],step=a<=b?1:-1;for(let n=a;;n+=step){out.push(n);if(n===b)break}return out}m=s.match(/^(\d+)\s*-\s*$/);if(m){const a=Number(m[1]);return a<=total?Array.from({length:total-a+1},(_,i)=>a+i):[]}m=s.match(/^\s*-\s*(\d+)$/);if(m){const b=Number(m[1]);return b>=1?Array.from({length:Math.min(total,b)},(_,i)=>i+1):[]}return null}
function parseRange(raw,total){if(!total)return null;const out=[],seen=new Set();for(const token of String(raw||'').split(',')){const values=parseAtom(token,total);if(!values||!values.length)return null;for(const n of values){if(!Number.isInteger(n)||n<1||n>total)return null;if(!seen.has(n)){seen.add(n);out.push(n-1)}}}return out.length?out:null}
function toast(text,ms=2600){const e=$('#status');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),ms)}
function setUiBusy(on){running=on;for(const id of['extractCurrent','extractRange']){const b=$('#'+id);if(b)b.disabled=on||$('#exportTop')?.disabled}if(on)toast(t('working'))}
function waitForBlob(get,timeout=120000){return new Promise((resolve,reject)=>{const start=Date.now(),tick=()=>{const blob=get();if(blob)return resolve(blob);if(Date.now()-start>timeout)return reject(new Error('export timeout'));setTimeout(tick,80)};tick()})}
async function captureEditedPdf(){const exportButton=$('#exportTop');if(!exportButton||exportButton.disabled)throw new Error('no pdf');const originalCreate=URL.createObjectURL.bind(URL),originalClick=HTMLAnchorElement.prototype.click;let captured=null;URL.createObjectURL=function(value){const url=originalCreate(value);if(value instanceof Blob&&value.type==='application/pdf')captured=value;return url};HTMLAnchorElement.prototype.click=function(){if(this.download&&/^edited-.*\.pdf$/i.test(this.download)&&String(this.href).startsWith('blob:'))return;return originalClick.call(this)};try{exportButton.click();return await waitForBlob(()=>captured)}finally{URL.createObjectURL=originalCreate;HTMLAnchorElement.prototype.click=originalClick}}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function safeLabel(value){return String(value||'pages').trim().replace(/[^0-9a-zA-Z_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'pages'}
async function extract(indexes,label){if(running)return;setUiBusy(true);try{const full=await captureEditedPdf(),src=await PDFLib.PDFDocument.load(await full.arrayBuffer()),out=await PDFLib.PDFDocument.create(),valid=indexes.filter(i=>i>=0&&i<src.getPageCount());if(!valid.length)throw new Error('empty');const copied=await out.copyPages(src,valid);copied.forEach(p=>out.addPage(p));out.setTitle('Extracted pages');out.setProducer('PDF WORKBENCH');out.setCreator('PDF WORKBENCH');const bytes=await out.save({useObjectStreams:true});download(`${safeLabel(label)}.pdf`,new Blob([bytes],{type:'application/pdf'}));toast((window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.saved||'PDF exported')}catch(e){console.warn(e);toast(t('failed'))}finally{setUiBusy(false)}}
function renderLabels(){const box=$('#extractBox');if(!box)return;box.querySelector('.extract-title').textContent=t('title');$('#extractRangeValue').placeholder=t('hint');$('#extractCurrent').textContent=t('current');$('#extractRange').textContent=t('range');box.querySelector('.extract-help').textContent=t('help')}
function updateButtons(){if(running)return;const disabled=$('#exportTop')?.disabled!==false;$('#extractCurrent').disabled=disabled;$('#extractRange').disabled=disabled}
function ensureStyle(){if(document.querySelector('link[data-pdf-workbench-extra]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='seo.css';l.dataset.pdfWorkbenchExtra='1';document.head.appendChild(l)}
function loadScript(src,attr){if(document.querySelector(`script[${attr}]`))return;const s=document.createElement('script');s.src=src;s.setAttribute(attr,'1');document.head.appendChild(s)}
function init(){ensureStyle();const side=$('.panel.side');if(!side||$('#extractBox'))return;const box=document.createElement('div');box.id='extractBox';box.className='extract-box';box.innerHTML='<strong class="extract-title"></strong><input id="extractRangeValue" class="extract-input" inputmode="text" value="1"><div class="extract-actions"><button class="button" id="extractCurrent" type="button"></button><button class="button" id="extractRange" type="button"></button></div><small class="extract-help"></small>';side.append(box);renderLabels();updateButtons();$('#extractCurrent').onclick=()=>{const n=Number($('#pageNumber')?.value||1);extract([Math.max(0,n-1)],`page-${n}`)};$('#extractRange').onclick=()=>{const raw=$('#extractRangeValue').value,indexes=parseRange(raw,totalPages());if(!indexes){toast(t('invalid'));return}extract(indexes,`pages-${safeLabel(raw)}`)};$('#extractRangeValue').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#extractRange').click()}});$('#languageSelect')?.addEventListener('change',()=>setTimeout(renderLabels));new MutationObserver(updateButtons).observe($('#exportTop'),{attributes:true,attributeFilter:['disabled']});loadScript('merge-pdf.js','data-pdf-merge');loadScript('image-to-pdf.js','data-image-pdf');loadScript('power-tools.js','data-power-tools');loadScript('ocr-pdf.js','data-ocr-pdf')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();