(()=>{'use strict';
const $=s=>document.querySelector(s);let running=false;
if(window.pdfjsLib&&!window.__pdfWorkbenchSafeDataClone){const originalLib=window.pdfjsLib,originalGetDocument=originalLib.getDocument.bind(originalLib);window.pdfjsLib={...originalLib,getDocument(source){if(source&&typeof source==='object'&&source.data instanceof Uint8Array)source={...source,data:source.data.slice()};return originalGetDocument(source)}};window.__pdfWorkbenchSafeDataClone=true}
const labels={ja:{title:'ページ抽出',hint:'例: 1-3,5,8',current:'現在ページ',range:'指定ページを書き出す',invalid:'ページ指定を確認してください',working:'編集内容を反映して抽出中…',failed:'ページ抽出に失敗しました'},en:{title:'Extract pages',hint:'e.g. 1-3,5,8',current:'Current page',range:'Export selected pages',invalid:'Check the page range',working:'Applying edits and extracting…',failed:'Could not extract pages'},zh:{title:'提取页面',hint:'例如 1-3,5,8',current:'当前页',range:'导出指定页面',invalid:'请检查页面范围',working:'正在应用编辑并提取…',failed:'页面提取失败'},ko:{title:'페이지 추출',hint:'예: 1-3,5,8',current:'현재 페이지',range:'지정 페이지 내보내기',invalid:'페이지 범위를 확인하세요',working:'편집 내용을 적용해 추출 중…',failed:'페이지 추출 실패'}};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(labels[lang()]||labels.en)[k]||k;
function totalPages(){const m=$('#pageTotal')?.textContent.match(/\d+/);return m?Number(m[0]):0}
function parseRange(raw,total){const out=[],seen=new Set();for(const token of String(raw||'').split(',')){const s=token.trim();if(!s)return null;const m=s.match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)return null;const a=Number(m[1]),b=m[2]?Number(m[2]):a;if(a<1||b<1||a>total||b>total)return null;const step=a<=b?1:-1;for(let n=a;;n+=step){if(!seen.has(n)){seen.add(n);out.push(n-1)}if(n===b)break}}return out.length?out:null}
function toast(text){const e=$('#status');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2600)}
function setUiBusy(on){running=on;for(const id of ['extractCurrent','extractRange']){const b=$('#'+id);if(b)b.disabled=on||$('#exportTop')?.disabled}if(on)toast(t('working'))}
function waitForBlob(get,timeout=120000){return new Promise((resolve,reject)=>{const start=Date.now(),tick=()=>{const blob=get();if(blob)return resolve(blob);if(Date.now()-start>timeout)return reject(new Error('export timeout'));setTimeout(tick,80)};tick()})}
async function captureEditedPdf(){const exportButton=$('#exportTop');if(!exportButton||exportButton.disabled)throw new Error('no pdf');const originalCreate=URL.createObjectURL.bind(URL),originalClick=HTMLAnchorElement.prototype.click;let captured=null;URL.createObjectURL=function(value){const url=originalCreate(value);if(value instanceof Blob&&value.type==='application/pdf')captured=value;return url};HTMLAnchorElement.prototype.click=function(){if(this.download&&/^edited-.*\.pdf$/i.test(this.download)&&String(this.href).startsWith('blob:'))return;return originalClick.call(this)};try{exportButton.click();return await waitForBlob(()=>captured)}finally{URL.createObjectURL=originalCreate;HTMLAnchorElement.prototype.click=originalClick}}
function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
async function extract(indexes,label){if(running)return;setUiBusy(true);try{const full=await captureEditedPdf(),src=await PDFLib.PDFDocument.load(await full.arrayBuffer()),out=await PDFLib.PDFDocument.create(),valid=indexes.filter(i=>i>=0&&i<src.getPageCount());if(!valid.length)throw new Error('empty');const copied=await out.copyPages(src,valid);copied.forEach(p=>out.addPage(p));out.setProducer('PDF WORKBENCH');out.setCreator('PDF WORKBENCH');const bytes=await out.save({useObjectStreams:true});download(`${label}.pdf`,new Blob([bytes],{type:'application/pdf'}));toast((window.PDFWB_I18N?.[lang()]||window.PDFWB_I18N?.en)?.saved||'PDF exported')}catch(e){console.warn(e);toast(t('failed'))}finally{setUiBusy(false)}}
function renderLabels(){const box=$('#extractBox');if(!box)return;box.querySelector('.extract-title').textContent=t('title');$('#extractRangeValue').placeholder=t('hint');$('#extractCurrent').textContent=t('current');$('#extractRange').textContent=t('range')}
function updateButtons(){if(running)return;const disabled=$('#exportTop')?.disabled!==false;$('#extractCurrent').disabled=disabled;$('#extractRange').disabled=disabled}
function init(){const side=$('.panel.side');if(!side||$('#extractBox'))return;const box=document.createElement('div');box.id='extractBox';box.className='extract-box';box.innerHTML='<strong class="extract-title"></strong><input id="extractRangeValue" class="extract-input" inputmode="numeric" value="1"><div class="extract-actions"><button class="button" id="extractCurrent" type="button"></button><button class="button" id="extractRange" type="button"></button></div><small>Uses the fully edited export, including page order, annotations and secure redaction.</small>';side.append(box);renderLabels();updateButtons();$('#extractCurrent').onclick=()=>{const n=Number($('#pageNumber')?.value||1);extract([Math.max(0,n-1)],`page-${n}`)};$('#extractRange').onclick=()=>{const indexes=parseRange($('#extractRangeValue').value,totalPages());if(!indexes){toast(t('invalid'));return}extract(indexes,'extracted-pages')};$('#languageSelect')?.addEventListener('change',()=>setTimeout(renderLabels));new MutationObserver(updateButtons).observe($('#exportTop'),{attributes:true,attributeFilter:['disabled']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();