(()=>{'use strict';
const $=s=>document.querySelector(s),DRAFT_KEY='sqlite-lite-query-draft-v1',RECENT_KEY='sqlite-lite-query-recent-v1',MAX_RECENT=20,MAX_SQL_BYTES=2*1024*1024;
const query=$('#query'),run=$('#run'),exportDb=$('#exportDb'),status=$('#status'),state=$('#dbState');if(!query||!run)return;
const ui={ja:{save:'SQL保存',open:'SQLを開く',recent:'最近のSQL',clear:'履歴消去',restored:'前回のSQLドラフトを復元しました',tooLarge:'SQLファイルは2MBまでです',elapsed:'実行時間'},en:{save:'Save SQL',open:'Open SQL',recent:'Recent SQL',clear:'Clear history',restored:'Restored your previous SQL draft',tooLarge:'SQL files are limited to 2 MB',elapsed:'Elapsed'},zh:{save:'保存 SQL',open:'打开 SQL',recent:'最近的 SQL',clear:'清除历史',restored:'已恢复上次 SQL 草稿',tooLarge:'SQL 文件最大 2MB',elapsed:'耗时'},ko:{save:'SQL 저장',open:'SQL 열기',recent:'최근 SQL',clear:'기록 지우기',restored:'이전 SQL 초안을 복원했습니다',tooLarge:'SQL 파일은 2MB까지 지원합니다',elapsed:'실행 시간'}};
const lang=()=>$('#languageSelect')?.value||'ja',t=k=>(ui[lang()]||ui.en)[k]||k;
function safeName(v){return(String(v||'query').trim().replace(/[\\/:*?"<>|\x00-\x1f]+/g,'-').slice(0,80)||'query')}
function download(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function loadRecent(){try{const v=JSON.parse(localStorage.getItem(RECENT_KEY)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'&&x.trim()).slice(0,MAX_RECENT):[]}catch{return[]}}
function storeRecent(sql){let list=loadRecent().filter(x=>x!==sql);list.unshift(sql);list=list.slice(0,MAX_RECENT);try{localStorage.setItem(RECENT_KEY,JSON.stringify(list))}catch{}renderRecent()}
function renderRecent(){const host=$('#persistentHistory');if(!host)return;const list=loadRecent();host.replaceChildren();if(!list.length){host.hidden=true;return}host.hidden=false;const head=document.createElement('div');head.className='pro-history-head';const strong=document.createElement('strong');strong.textContent=t('recent');const clear=document.createElement('button');clear.type='button';clear.className='button';clear.textContent=t('clear');clear.onclick=()=>{localStorage.removeItem(RECENT_KEY);renderRecent()};head.append(strong,clear);host.append(head);const body=document.createElement('div');body.className='pro-history-list';for(const sql of list){const b=document.createElement('button');b.type='button';b.className='pro-query';b.textContent=sql.replace(/\s+/g,' ').slice(0,120);b.title=sql;b.onclick=()=>{query.value=sql;query.focus();query.dispatchEvent(new Event('input',{bubbles:true}))};body.append(b)}host.append(body)}
function relabel(){const save=$('#saveSql'),open=$('#openSqlButton'),perf=$('#queryPerf');if(save)save.textContent=t('save');if(open)open.textContent=t('open');if(perf&&perf.dataset.ms)perf.textContent=`${t('elapsed')}: ${perf.dataset.ms} ms`;renderRecent()}
function mount(){const actions=document.querySelector('.query-actions');if(!actions||$('#saveSql'))return;const openInput=document.createElement('input');openInput.id='openSql';openInput.type='file';openInput.accept='.sql,text/plain,application/sql';openInput.hidden=true;const open=document.createElement('button');open.id='openSqlButton';open.type='button';open.className='button';const save=document.createElement('button');save.id='saveSql';save.type='button';save.className='button';actions.append(save,open,openInput);const perf=document.createElement('span');perf.id='queryPerf';perf.className='pro-perf';document.querySelector('.work-head')?.append(perf);const persistent=document.createElement('div');persistent.id='persistentHistory';persistent.className='pro-history';persistent.hidden=true;$('#history')?.after(persistent);const style=document.createElement('style');style.textContent='.pro-perf{font-size:10px;color:var(--muted);white-space:nowrap}.pro-history{border-top:1px solid var(--rule);padding:8px 0}.pro-history-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:6px;font-size:10px}.pro-history-head .button{padding:5px 8px}.pro-history-list{display:flex;gap:5px;overflow:auto;padding-bottom:2px}.pro-query{max-width:260px;flex:0 0 auto;border:1px solid var(--rule);border-radius:7px;background:var(--paper);color:var(--ink);padding:6px 8px;font:9px var(--font-body);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;cursor:pointer}.pro-query:hover{border-color:var(--accent);color:var(--accent)}';document.head.append(style);save.onclick=()=>download(`${safeName($('#dbName')?.textContent||'query')}.sql`,new Blob([query.value.trimEnd()+'\n'],{type:'text/plain;charset=utf-8'}));open.onclick=()=>openInput.click();openInput.onchange=async()=>{const file=openInput.files?.[0];openInput.value='';if(!file)return;if(file.size>MAX_SQL_BYTES){status.textContent=t('tooLarge');return}try{query.value=await file.text();query.dispatchEvent(new Event('input',{bubbles:true}));query.focus()}catch{}};relabel()}
let saveTimer=0;query.addEventListener('input',()=>{clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(DRAFT_KEY,query.value)}catch{}},180)});
let started=0;run.addEventListener('click',()=>{const sql=query.value.trim();if(sql)storeRecent(sql);started=performance.now()},{capture:true});
new MutationObserver(()=>{if(started&&!run.disabled){const ms=Math.max(0,Math.round(performance.now()-started));started=0;const perf=$('#queryPerf');if(perf){perf.dataset.ms=String(ms);perf.textContent=`${t('elapsed')}: ${ms} ms`}}}).observe(run,{attributes:true,attributeFilter:['disabled']});
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return;const key=e.key.toLowerCase();if(e.shiftKey&&key==='s'){e.preventDefault();$('#saveSql')?.click()}else if(e.shiftKey&&key==='o'){e.preventDefault();$('#openSqlButton')?.click()}else if(key==='s'){e.preventDefault();if(!exportDb.disabled)exportDb.click()}},{capture:true});
window.addEventListener('beforeunload',e=>{const text=(state?.textContent||'').toLowerCase();if(/変更|modified|transaction|已修改|事务|변경|트랜잭션/.test(text)){e.preventDefault();e.returnValue=''}});
$('#languageSelect')?.addEventListener('change',()=>setTimeout(relabel));
mount();
try{const draft=localStorage.getItem(DRAFT_KEY);if(draft&&draft.trim()&&draft!==query.value){query.value=draft;status.textContent=t('restored')}}catch{}
renderRecent();
})();