(()=>{'use strict';
const $=s=>document.querySelector(s),states=new Set(['トランザクション中','Transaction active','事务进行中','트랜잭션 진행 중']);
const messages={ja:'トランザクション中はDB保存できません。COMMITまたはROLLBACKしてから保存してください。',en:'Database export is disabled during an active transaction. COMMIT or ROLLBACK first.',zh:'事务进行中时无法保存数据库。请先 COMMIT 或 ROLLBACK。',ko:'트랜잭션 진행 중에는 DB를 저장할 수 없습니다. 먼저 COMMIT 또는 ROLLBACK 하세요.'};
function lang(){return $('#languageSelect')?.value||document.documentElement.lang||'en'}
function active(){return states.has(($('#dbState')?.textContent||'').trim())}
function sync(){const b=$('#exportDb');if(!b)return;b.dataset.transactionBlocked=active()?'true':'false';b.title=active()?(messages[lang()]||messages.en):''}
function commentTailOnly(s){let i=0;while(i<s.length){while(i<s.length&&/\s/.test(s[i]))i++;if(i>=s.length)return true;if(s.startsWith('--',i)){const n=s.indexOf('\n',i+2);i=n<0?s.length:n+1;continue}if(s.startsWith('/*',i)){const n=s.indexOf('*/',i+2);if(n<0)return false;i=n+2;continue}return false}return true}
function normalizeTrailingComment(sql){sql=String(sql||'');let state='normal',lastSemi=-1;for(let i=0;i<sql.length;i++){const c=sql[i],n=sql[i+1];if(state==='line'){if(c==='\n')state='normal';continue}if(state==='block'){if(c==='*'&&n==='/'){state='normal';i++}continue}if(state==='single'){if(c==="'"&&n==="'"){i++;continue}if(c==="'")state='normal';continue}if(state==='double'){if(c==='"'&&n==='"'){i++;continue}if(c==='"')state='normal';continue}if(state==='backtick'){if(c==='`')state='normal';continue}if(state==='bracket'){if(c===']')state='normal';continue}if(c==='-'&&n==='-'){state='line';i++;continue}if(c==='/'&&n==='*'){state='block';i++;continue}if(c==="'"){state='single';continue}if(c==='"'){state='double';continue}if(c==='`'){state='backtick';continue}if(c==='['){state='bracket';continue}if(c===';')lastSemi=i}if(lastSemi>=0&&commentTailOnly(sql.slice(lastSemi+1)))return sql.slice(0,lastSemi+1).trimEnd();return sql}
function normalizeQuery(){const q=$('#query');if(q)q.value=normalizeTrailingComment(q.value)}
function init(){const b=$('#exportDb'),state=$('#dbState'),q=$('#query');if(!b||!state)return;b.addEventListener('click',e=>{if(!active())return;e.preventDefault();e.stopImmediatePropagation();const s=$('#status');if(s)s.textContent=messages[lang()]||messages.en},{capture:true});for(const id of ['run','explainPlan'])$('#'+id)?.addEventListener('click',normalizeQuery,{capture:true});q?.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))normalizeQuery()},{capture:true});new MutationObserver(sync).observe(state,{childList:true,subtree:true,characterData:true});$('#languageSelect')?.addEventListener('change',()=>setTimeout(sync));sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();